config/routes.rb
Todos::Application.routes.draw do
  root to: 'high_voltage/pages#show', id: 'homepage'
  resource :session, only: [:create]
  resources :todos, only: [:index, :new, :create] do
    resource :completion, only: [:create]
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :description, :owner_email

  def user=(new_user)
    self.owner_email = new_user.email
  end
end

app/models/user.rb
class User
  attr_reader :email

  def initialize(email)
    @email = email
  end

  def todos
    Todo.where(owner_email: email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def sign_in_as(email)
    session[:current_email] = email
  end

  def current_user
    User.new(session[:current_email])
  end
  helper_method :current_user
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def create
    todo = current_user.todos.find(params[:todo_id])
    todo.touch :completed_at
    redirect_to todos_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    sign_in_as(params[:session][:email_address])
    redirect_to todos_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(params[:todo])
    @todo.user = current_user
    @todo.save
    redirect_to todos_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Todos
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %p.welcome= "Welcome, #{current_user.email}"
    = yield

app/views/pages/homepage.html.haml
%p{:'data-role' => 'description'}
  This is an app to manage todos.

= form_for :session, url: session_path do |form|
  = form.label :email_address
  = form.text_field :email_address
  = form.submit "Sign In"

app/views/todos/index.html.haml
%ul
  - @todos.each do |todo|
    %li.todo{class: "#{'completed' if todo.completed_at?}"}
      = todo.description
      = link_to 'Complete', todo_completion_path(todo), method: :post

= link_to 'Add a new todo', new_todo_path

app/views/todos/new.html.haml
= form_for @todo do |form|
  = form.label :description
  = form.text_field :description
  = form.submit 'Create todo'
  